version: '3'
services:

  redis_cache:
    restart: always
    image: redis:alpine
    container_name: redis_cache

  publisher_box:
    restart: always
    build: publisher_box
    depends_on:
      - redis_cache

  processor_box:
    restart: always
    build: processor_box
    depends_on:
      - redis_cache
