version: '3'
services:

  redis_cache:
    restart: always
    image: redis:alpine
    container_name: redis_cache

  publisher_box:
    restart: on-failure
    build: publisher_box
    depends_on:
      - redis_cache

  processor_box:
    restart: on-failure
    build: processor_box
    depends_on:
      - redis_cache

  final_box:
    restart: on-failure
    build: final_box
    depends_on:
      - redis_cache
      - publisher_box
      - processor_box
